name: ci

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'
      - name: Dar permissão de execução ao mvnw
        run: chmod +x ./mvnw

      - name: Build com Maven
        run: ./mvnw clean install

      - name: Rodar testes
        run: ./mvnw test